// Originally generated by scripts/port-map.py from the standalone map, then hand-edited. Edit the data in
// data/erd.v5.json; edit behaviour here. Plain JS on purpose: this is the vanilla map engine, mounted by
// components/ErdMap.tsx. Motion (viewport tweens, node intro, selection pulse) uses anime.js and is skipped
// when the OS asks for reduced motion.
import { animate, engine } from "animejs";
engine.pauseOnDocumentHidden = false; // viewport tweens must finish even if the tab is briefly hidden

const I = (d, cls) => `<svg${cls ? ` class="${cls}"` : ""} viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${d}</svg>`;
const IC = {
  search: I('<circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/>'),
  chev: I('<path d="m6 9 6 6 6-6"/>'),
  fit: I('<path d="M8 3H5a2 2 0 0 0-2 2v3"/><path d="M21 8V5a2 2 0 0 0-2-2h-3"/><path d="M3 16v3a2 2 0 0 0 2 2h3"/><path d="M16 21h3a2 2 0 0 0 2-2v-3"/>'),
  plus: I('<path d="M5 12h14"/><path d="M12 5v14"/>'),
  minus: I('<path d="M5 12h14"/>'),
  info: I('<circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/>'),
  click: I('<path d="M14 4.1 12 6"/><path d="m5.1 8-2.9-.8"/><path d="m6 12-1.9 2"/><path d="M7.2 2.2 8 5.1"/><path d="M9.037 9.69a.498.498 0 0 1 .653-.653l11 4.5a.5.5 0 0 1-.074.949l-4.349 1.041a1 1 0 0 0-.74.739l-1.04 4.35a.5.5 0 0 1-.95.074z"/>'),
  branch: I('<line x1="6" x2="6" y1="3" y2="15"/><circle cx="18" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><path d="M18 9a9 9 0 0 1-9 9"/>'),
  route: I('<circle cx="6" cy="19" r="3"/><path d="M9 19h8.5a3.5 3.5 0 0 0 0-7h-11a3.5 3.5 0 0 1 0-7H15"/><circle cx="18" cy="5" r="3"/>'),
  chat: I('<path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z"/>'),
  hide: I('<rect width="18" height="18" x="3" y="3" rx="2"/><path d="M15 3v18"/><path d="m8 9 3 3-3 3"/>'),
  show: I('<rect width="18" height="18" x="3" y="3" rx="2"/><path d="M15 3v18"/><path d="m10 15-3-3 3-3"/>'),
  left: I('<path d="m12 19-7-7 7-7"/><path d="M19 12H5"/>'),
  right: I('<path d="M5 12h14"/><path d="m12 5 7 7-7 7"/>'),
  x: I('<path d="M18 6 6 18"/><path d="m6 6 12 12"/>'),
  eye: I('<path d="M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0"/><circle cx="12" cy="12" r="3"/>'),
};

export const SKELETON = `
<div id="app">
  <header>
    <h1>NPLify Unified ERD <small>P0 data model · draft v5.5 · 68 tables + 9 views</small></h1>
    <div class="tools">
      <div class="search">${IC.search}<input id="q" type="search" placeholder="Find an entity or field…" aria-label="Find entity or field" autocomplete="off"><kbd>/</kbd></div>
      <div class="selwrap"><select id="walkSel" aria-label="Walkthrough"><option value="">Walk a data flow…</option></select>${IC.chev}</div>
      <span class="grow"></span>
      <button class="btn" id="bFit" title="Fit the whole map in view">${IC.fit}Fit</button>
      <button class="btn ghost" id="bClear" title="Clear search, selection and trace">${IC.x}Clear</button>
      <div class="menu">
        <button class="btn" id="bView" aria-haspopup="true" aria-expanded="false" title="What to show on the map">${IC.eye}View<span class="count" id="viewCount"></span>${IC.chev}</button>
        <div class="pop" id="viewPop" hidden>
          <label class="tog"><input type="checkbox" id="tAll"> <span>All fields<small>Show every column, not only keys</small></span></label>
          <label class="tog"><input type="checkbox" id="tLbl"> <span>All labels<small>Name every link, not only highlighted ones</small></span></label>
          <label class="tog"><input type="checkbox" id="tActor"> <span>Approver links<small>Dotted links to the USER who approves or confirms</small></span></label>
          <label class="tog"><input type="checkbox" id="tPoly" checked> <span>Polymorphic links<small>Links resolved by type + id</small></span></label>
          <label class="tog"><input type="checkbox" id="tView" checked> <span>Derived views<small>Grey dashed boxes, computed and never stored</small></span></label>
        </div>
      </div>
    </div>
    <div class="tools row2">
      <span class="lbl-focus">Focus</span>
      <div class="chips" id="domchips"></div>
    </div>
  </header>
  <main>
    <div id="stage">
      <svg id="map" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Unified entity-relationship map of the NPLify schema. Click an entity to see its fields and the entities it feeds or is fed by.">
        <defs>
          <marker id="m-owns" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="9" markerHeight="9" orient="auto" markerUnits="userSpaceOnUse"><path d="M0,1 L9,5 L0,9 z" fill="var(--k-owns)"/></marker>
          <marker id="m-owns-s" viewBox="0 0 12 10" refX="0" refY="5" markerWidth="12" markerHeight="10" orient="auto" markerUnits="userSpaceOnUse"><path d="M0,5 L5,1 L10,5 L5,9 z" fill="var(--k-owns)"/></marker>
          <marker id="m-refs" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="9" markerHeight="9" orient="auto" markerUnits="userSpaceOnUse"><path d="M1,1 L9,5 L1,9" fill="none" stroke="var(--k-refs)" stroke-width="1.4"/></marker>
          <marker id="m-poly" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="9" markerHeight="9" orient="auto" markerUnits="userSpaceOnUse"><path d="M1,1 L9,5 L1,9" fill="none" stroke="var(--k-poly)" stroke-width="1.4"/></marker>
          <marker id="m-poly-s" viewBox="0 0 10 10" refX="1" refY="5" markerWidth="10" markerHeight="10" orient="auto" markerUnits="userSpaceOnUse"><circle cx="5" cy="5" r="3.5" fill="var(--canvas)" stroke="var(--k-poly)" stroke-width="1.4"/></marker>
          <marker id="m-view" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="9" markerHeight="9" orient="auto" markerUnits="userSpaceOnUse"><path d="M1,1 L9,5 L1,9" fill="none" stroke="var(--k-view)" stroke-width="1.4"/></marker>
          <marker id="m-actor" viewBox="0 0 10 10" refX="5" refY="5" markerWidth="8" markerHeight="8" orient="auto" markerUnits="userSpaceOnUse"><circle cx="5" cy="5" r="2.5" fill="var(--k-actor)"/></marker>
          <marker id="m-self" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="9" markerHeight="9" orient="auto" markerUnits="userSpaceOnUse"><path d="M0,1 L9,5 L0,9 z" fill="var(--k-self)"/></marker>
          <marker id="m-hi" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="10" markerHeight="10" orient="auto" markerUnits="userSpaceOnUse"><path d="M0,1 L9,5 L0,9 z" fill="var(--hi)"/></marker>
          <marker id="m-hi-s" viewBox="0 0 12 10" refX="0" refY="5" markerWidth="12" markerHeight="10" orient="auto" markerUnits="userSpaceOnUse"><path d="M0,5 L5,1 L10,5 L5,9 z" fill="var(--hi)"/></marker>
          <filter id="nglow" x="-25%" y="-25%" width="150%" height="150%" color-interpolation-filters="sRGB"><feDropShadow dx="0" dy="0" stdDeviation="7" flood-color="#ff5a2e" flood-opacity="0.55"/></filter>
          <filter id="nglow-a" x="-25%" y="-25%" width="150%" height="150%" color-interpolation-filters="sRGB"><feDropShadow dx="0" dy="0" stdDeviation="6" flood-color="#6366f1" flood-opacity="0.5"/></filter>
        </defs>
        <g id="world">
          <g id="lanes"></g>
          <g id="edges"></g>
          <g id="nodes"></g>
          <g id="labels"></g>
        </g>
      </svg>
      <div id="hint" class="ov">${IC.info}<span>Drag to pan, scroll to zoom. Hover an entity to see its links; click to pin it and read its details.</span></div>
      <button class="btn" id="pOpen">${IC.show}Show details</button>
      <div id="zoomctl" class="ov">
        <button class="btn" id="zIn" aria-label="Zoom in" title="Zoom in">${IC.plus}</button>
        <button class="btn" id="zOut" aria-label="Zoom out" title="Zoom out">${IC.minus}</button>
        <button class="btn" id="zFit" aria-label="Fit to view" title="Fit to view">${IC.fit}</button>
      </div>
      <div id="legend" class="ov">
        <b>Associations <button type="button" id="legTog" aria-label="Collapse legend">hide</button></b>
        <div class="lg">
          <svg viewBox="0 0 34 12"><path d="M3,6 H31" stroke="var(--k-owns)" stroke-width="1.8" marker-start="url(#m-owns-s)" marker-end="url(#m-owns)"/></svg><span>owns · parent → child (composition)</span>
          <svg viewBox="0 0 34 12"><path d="M3,6 H31" stroke="var(--k-refs)" stroke-width="1.1" marker-end="url(#m-refs)"/></svg><span>references · lookup / stamped FK</span>
          <svg viewBox="0 0 34 12"><path d="M3,6 H31" stroke="var(--k-poly)" stroke-width="1.2" stroke-dasharray="5 3" marker-start="url(#m-poly-s)" marker-end="url(#m-poly)"/></svg><span>polymorphic · by type + id</span>
          <svg viewBox="0 0 34 12"><path d="M3,6 H31" stroke="var(--k-view)" stroke-width="1.2" stroke-dasharray="8 4" marker-end="url(#m-view)"/></svg><span>derived · feeds a view (never stored)</span>
          <svg viewBox="0 0 34 12"><path d="M3,6 H31" stroke="var(--k-actor)" stroke-width="1" stroke-dasharray="1.5 3" marker-end="url(#m-actor)"/></svg><span>actor · approved / confirmed by USER</span>
        </div>
        <div class="doms" id="legdoms"></div>
      </div>
    </div>
    <aside id="panel" aria-live="polite">
      <div id="pHead"><div class="ptabs" role="tablist"><span class="ink"></span><button class="ptab on" data-tab="details" role="tab">Details</button><button class="ptab" data-tab="ask" role="tab">Ask the ERD</button><button class="ptab" data-tab="oq" role="tab">Open questions</button></div><button class="btn ghost" id="pClose" aria-label="Hide panel" title="Hide panel">${IC.hide}</button></div>
      <div class="empty welcome">
        <div class="tip"><i>${IC.click}</i><p>Hover an entity to see its connections. Click to pin it.<small>Pinning opens the full data dictionary, what feeds it and what it feeds. Click again to unpin.</small></p></div>
        <div class="tip"><i>${IC.branch}</i><p>Arrows point the way data flows.<small>From the referenced row into the row that stores the foreign key. Use <em>Trace downstream</em> to light up everything an entity's data reaches.</small></p></div>
        <div class="tip"><i>${IC.route}</i><p>Walk a data flow from the toolbar.<small>Follow a deal step by step from quote to confirmation. Grey dashed boxes are derived views, computed and never stored.</small></p></div>
        <div class="tip"><i>${IC.chat}</i><p>Ask the ERD anything.<small>The assistant answers only from the model, the decision record, the Understanding document and NPL's fee practice, and points to entities on the map.</small></p></div>
      </div>
      <div id="chat" hidden>
        <div id="chatLog" aria-live="polite"></div>
        <div id="chatSug"></div>
        <form id="chatForm">
          <textarea id="chatIn" rows="2" placeholder="Ask anything about the ERD…" aria-label="Question"></textarea>
          <button class="btn primary" id="chatSend" type="submit">Ask</button>
          <button class="btn" id="chatStop" type="button" hidden>Stop</button>
        </form>
        <div id="chatMeta"><span id="chatNote">Answers come only from the ERD v5.5, the review decision record (D1–D45), the Understanding document, NPL’s fee-practice notes and the scenario catalogue. Conversations are recorded so New XP can see what is asked and answered.</span><button class="btn ghost" id="chatClear" type="button" style="padding:3px 8px">New chat</button></div>
      </div>
      <div id="oq" hidden></div>
    </aside>
  </main>
  <div id="walk">
    <div class="bar"></div>
    <div class="pos" id="wPos"></div>
    <div class="txt" id="wTxt"></div>
    <div class="nav">
      <button class="btn" id="wPrev">${IC.left}Prev</button>
      <button class="btn primary" id="wNext">Next ${IC.right}</button>
      <button class="btn ghost" id="wExit" title="Exit walkthrough">${IC.x}</button>
    </div>
  </div>
</div>
`;

export function mountErdMap(root, DATA, cfg) {
const {DOMS,COLS,E,ORDER,R,INV,WALKS,OPENQ,SCENARIOS,SCENARIO_V4}=DATA;
cfg=Object.assign({askUrl:'/api/ask',flagsUrl:'/api/flags',feedbackUrl:'/api/feedback',flaggingEnabled:false,visitor:false,onEvent:null},cfg||{});
root.innerHTML=SKELETON;
if(cfg.visitor){root.querySelector('#app').classList.add('visitor');const t=root.querySelector('.ptab[data-tab=oq]');if(t)t.remove();
  root.querySelector('#chatNote').textContent='Answers come only from the data model and its supporting documents. Conversations are recorded.';
  root.querySelector('header h1 small').textContent='P0 data model'}
const RM=typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches;
const cleanups=[];
/* ------------------------------------------------------------------ layout */
const W=236, HEAD=26, ROW=17, PAD=6, PITCH=340, X0=40, Y0=70, VGAP=26, RX=7;
const svg=root.querySelector('#map'), world=root.querySelector('#world');
const gL=root.querySelector('#lanes'), gE=root.querySelector('#edges'), gN=root.querySelector('#nodes'), gLb=root.querySelector('#labels');
const NS='http://www.w3.org/2000/svg';
const el=(t,a={},p)=>{const n=document.createElementNS(NS,t);for(const k in a)n.setAttribute(k,a[k]);if(p)p.appendChild(n);return n};
const $=(id)=>root.querySelector('#'+id);
let showAll=false;
const state={sel:null,hover:null,domOff:new Set(),walk:null,step:0,trace:null,q:''};
const nodes={}, edges=[];

function visibleRows(name){const e=E[name];return showAll||e.d==='view'?e.f:e.f.filter(r=>r[2])}
function layout(){
  const colY={};
  for(const c in ORDER){let y=Y0;for(const n of ORDER[c]){const rows=visibleRows(n);const h=HEAD+rows.length*ROW+PAD;nodes[n]={x:X0+c*PITCH,y,w:W,h,rows};y+=h+VGAP}colY[c]=y}
  return Math.max(...Object.values(colY));
}
function rowY(name,field){const n=nodes[name];const i=n.rows.findIndex(r=>r[0]===field);return i<0?n.y+HEAD/2:n.y+HEAD+i*ROW+ROW/2}

function drawLanes(maxY){
  gL.innerHTML='';
  COLS.forEach((c,i)=>{const x=X0+i*PITCH;
    el('text',{x,y:34,class:'lane-title'},gL).textContent=c.t;
    el('text',{x,y:50,class:'lane-sub'},gL).textContent=c.s;
    if(i>0)el('line',{x1:x-52,y1:16,x2:x-52,y2:maxY+20,class:'lane-rule','stroke-dasharray':'2 6'},gL);
  });
}
function drawNodes(){
  gN.innerHTML='';
  for(const name in E){const e=E[name],n=nodes[name];
    const g=el('g',{class:'node'+(e.d==='view'?' view':''),'data-id':name,transform:`translate(${n.x},${n.y})`},gN);
    const inner=el('g',{class:'in'},g);
    el('rect',{class:'sh',x:0,y:2,width:n.w,height:n.h,rx:RX},inner);   // fake drop shadow: no SVG filter (slow in Safari)
    el('rect',{class:'body',width:n.w,height:n.h,rx:RX},inner);
    el('rect',{class:'head',width:n.w,height:HEAD,rx:RX,fill:DOMS[e.d].c},inner);
    el('rect',{width:n.w,height:RX,y:HEAD-RX,fill:DOMS[e.d].c},inner);
    el('text',{class:'name',x:9,y:17},inner).textContent=name;
    n.rows.forEach((r,i)=>{const y=HEAD+i*ROW;
      if(i%2)el('rect',{class:'rowbg',x:1,y,width:n.w-2,height:ROW},inner);
      const t=el('text',{class:'row',x:9,y:y+12},inner);
      if(r[1]){const ty=el('tspan',{class:'ty'},t);ty.textContent=r[1]+' ';}
      const nm=el('tspan',{},t);nm.textContent=r[0];
      if(r[2]){const k=el('tspan',{class:'key'},t);k.textContent=' '+r[2];}
    });
    const ring=el('rect',{class:'ring',x:-4,y:-4,width:n.w+8,height:n.h+8,rx:RX+3},g);
    g.addEventListener('click',ev=>{ev.stopPropagation();select(name)});
    g.addEventListener('mouseenter',()=>hover(name));
    g.addEventListener('mouseleave',()=>hover(null));
    n.g=g;n.inner=inner;n.ring=ring;
  }
}
function edgePath(ed){
  const s=nodes[ed.s],t=nodes[ed.t];
  if(ed.s===ed.t){const x=s.x+s.w,y1=rowY(ed.s,'id'),y2=rowY(ed.t,ed.fk);return {d:`M${x},${y1} C${x+70},${y1-10} ${x+70},${y2+10} ${x},${y2}`,mx:x+54,my:(y1+y2)/2}}
  const sy=s.y+HEAD/2, ty=rowY(ed.t,ed.fk);
  let sx,tx;
  const dc=E[ed.t].col-E[ed.s].col;
  if(dc>0){sx=s.x+s.w;tx=t.x}else if(dc<0){sx=s.x;tx=t.x+t.w}else{sx=s.x+s.w;tx=t.x+t.w}
  if(dc===0){const k=60;return {d:`M${sx},${sy} C${sx+k},${sy} ${tx+k},${ty} ${tx},${ty}`,mx:sx+k*0.75,my:(sy+ty)/2}}
  const k=Math.max(40,Math.abs(tx-sx)*0.45)*(dc>0?1:-1);
  return {d:`M${sx},${sy} C${sx+k},${sy} ${tx-k},${ty} ${tx},${ty}`,mx:(sx+tx)/2,my:(sy+ty)/2}
}
function drawEdges(){
  gE.innerHTML='';gLb.innerHTML='';edges.length=0;
  R.forEach((r,i)=>{const ed={s:r[0],t:r[1],k:r[2],fk:r[3],label:r[4],card:r[5],v:r[6],i};
    const p=edgePath(ed);
    ed.hit=el('path',{d:p.d,class:'edge-hit'},gE);
    ed.el=el('path',{d:p.d,class:'edge '+ed.k,'marker-end':`url(#m-${ed.k})`},gE);
    if(ed.k==='owns')ed.el.setAttribute('marker-start','url(#m-owns-s)');
    if(ed.k==='poly')ed.el.setAttribute('marker-start','url(#m-poly-s)');
    const lb=el('g',{class:'lbl'},gLb);
    const t=el('text',{x:p.mx,y:p.my-3,'text-anchor':'middle'},lb);t.textContent=ed.label;
    const c=el('text',{x:p.mx,y:p.my+9,'text-anchor':'middle',class:'card'},lb);c.textContent=ed.card+(ed.fk?'  ·  '+ed.fk:'');
    ed.lb=lb;
    ed.hit.addEventListener('mouseenter',()=>{lb.classList.add('show');ed.el.classList.add('hi')});
    ed.hit.addEventListener('mouseleave',()=>{if(!ed.keep){lb.classList.remove('show');ed.el.classList.remove('hi')}});
    ed.hit.addEventListener('click',ev=>{ev.stopPropagation();select(ed.t,ed)});
    edges.push(ed);
  });
}
function build(){const maxY=layout();drawLanes(maxY);drawEdges();drawNodes();applyVisibility();applyHighlight();return maxY}

/* ------------------------------------------------------------------ motion helpers */
let introDone=false;
function intro(){
  // CSS keyframes (see .intro in globals.css): they run on the compositor and cannot stall if the tab is hidden.
  if(RM||introDone)return;introDone=true;
  let i=0;for(const name in E){nodes[name].inner.style.setProperty('--d',(i++*9)+'ms')}
  svg.classList.add('intro');
  const t=setTimeout(()=>{svg.classList.remove('intro');for(const name in E)nodes[name].inner.style.removeProperty('--d')},i*9+1200);
  cleanups.push(()=>clearTimeout(t));
}
function pulse(name){
  if(RM)return;const n=nodes[name];if(!n||!n.ring)return;
  const r=n.ring;r.classList.remove('go');void r.getBoundingClientRect();r.classList.add('go');
}
function panelIn(){pBody.classList.remove('pb-in');void pBody.offsetWidth;pBody.classList.add('pb-in')}

/* ------------------------------------------------------------------ visibility + highlight */
const tActor=$('tActor'),tPoly=$('tPoly'),tView=$('tView'),tLbl=$('tLbl');
function edgeVisible(ed){
  if(ed.k==='actor'&&!tActor.checked)return false;
  if(ed.k==='poly'&&!tPoly.checked)return false;
  if(ed.k==='view'&&!tView.checked)return false;
  if(E[ed.s].d==='view'&&!tView.checked)return false;
  if(E[ed.t].d==='view'&&!tView.checked)return false;
  return true;
}
function applyVisibility(){
  for(const name in E){const vis=!(E[name].d==='view'&&!tView.checked);nodes[name].g.style.display=vis?'':'none'}
  edges.forEach(ed=>{const v=edgeVisible(ed);ed.el.classList.toggle('hidden',!v);ed.hit.style.display=v?'':'none';ed.lb.classList.toggle('hidden',!v)});
}
function applyHighlight(){
  const focus=state.sel||state.hover;
  const walking=state.walk!==null;
  const trace=state.trace;
  const q=state.q;
  // nodes
  for(const name in E){const g=nodes[name].g;
    g.classList.remove('dim','sel','hover','step','visited','hit');
    let keep=true;
    if(state.domOff.size&&state.domOff.has(E[name].d))keep=false;
    if(q){if(matches(name,q))g.classList.add('hit');else keep=false}
    if(trace){if(!trace.nodes.has(name))keep=false}
    else if(walking){const steps=WALKS[state.walk].steps.map(s=>s[0]);const idx=steps.indexOf(name);
      if(idx<0)keep=false;else if(idx===state.step)g.classList.add('step');else if(idx<state.step)g.classList.add('visited');else keep=false;
      if(idx>state.step)keep=false}
    else if(focus){const nb=neighbours(focus);if(name!==focus&&!nb.has(name))keep=false}
    if(name===state.sel)g.classList.add('sel');else if(name===state.hover)g.classList.add('hover');
    if(!keep)g.classList.add('dim');
  }
  // edges
  edges.forEach(ed=>{ed.el.classList.remove('dim','hi','flow');ed.keep=false;ed.lb.classList.toggle('show',tLbl.checked);
    let keep=true,hi=false,flow=false;
    if(state.domOff.size&&(state.domOff.has(E[ed.s].d)||state.domOff.has(E[ed.t].d)))keep=false;
    if(q){if(!(matches(ed.s,q)||matches(ed.t,q)))keep=false}
    if(trace){if(trace.edges.has(ed)){flow=true}else keep=false}
    else if(walking){const steps=WALKS[state.walk].steps.map(s=>s[0]);const a=steps.indexOf(ed.s),b=steps.indexOf(ed.t);
      const pair=(a>=0&&b>=0&&Math.abs(a-b)===1&&Math.max(a,b)<=state.step);
      if(pair){flow=true}else keep=false}
    else if(focus){if(ed.s===focus||ed.t===focus)hi=true;else keep=false}
    if(!keep)ed.el.classList.add('dim');
    if(hi){ed.el.classList.add('hi');ed.keep=true;ed.lb.classList.add('show');ed.el.setAttribute('marker-end','url(#m-hi)');if(ed.k==='owns')ed.el.setAttribute('marker-start','url(#m-hi-s)')}
    else if(flow){ed.el.classList.add('flow');ed.keep=true;ed.lb.classList.add('show');ed.el.setAttribute('marker-end','url(#m-hi)');if(ed.k==='owns')ed.el.setAttribute('marker-start','url(#m-hi-s)')}
    else{ed.el.setAttribute('marker-end',`url(#m-${ed.k})`);if(ed.k==='owns')ed.el.setAttribute('marker-start','url(#m-owns-s)')}
  });
}
function neighbours(name){const s=new Set();edges.forEach(ed=>{if(!edgeVisible(ed))return;if(ed.s===name)s.add(ed.t);if(ed.t===name)s.add(ed.s)});return s}
function matches(name,q){if(name.toLowerCase().includes(q))return true;return E[name].f.some(r=>r[0].toLowerCase().includes(q))}

/* ------------------------------------------------------------------ selection + panel */
const panel=$('panel');
const mainEl=root.querySelector('main');
function setPanel(open){mainEl.classList.toggle('collapsed',!open);try{localStorage.setItem('erd-panel',open?'1':'0')}catch(e){}}
$('pClose').addEventListener('click',()=>setPanel(false));
$('pOpen').addEventListener('click',()=>setPanel(true));
try{if(localStorage.getItem('erd-panel')==='0')setPanel(false)}catch(e){}
let previewed=null;
function hover(name){
  state.hover=name;
  if(state.sel||state.walk!==null||state.trace)return;           // locked, walking or tracing: hover does nothing
  applyHighlight();
  if(name&&name!==previewed){previewed=name;renderPanel(name,null)} // the panel keeps the last preview so it can be read
}
function select(name,viaEdge,opts){
  if(state.sel===name&&!viaEdge&&!(opts&&opts.force)){state.sel=null;state.trace=null;state.hover=name;previewed=name;applyHighlight();renderPanel(name,null);cfg.onEvent&&cfg.onEvent('entity_unpinned',{entity:name});return}
  state.trace=null;state.sel=name;previewed=name;applyHighlight();renderPanel(name,viaEdge);pulse(name);if(!(opts&&opts.stayTab))setTab('details');if(state.walk===null)fitTo([name,...neighbours(name)]);cfg.onEvent&&cfg.onEvent('entity_pinned',{entity:name,via:viaEdge?'edge':'click'})}
function clearAll(){state.sel=null;state.trace=null;state.hover=null;previewed=null;exitWalk();applyHighlight();pBody.innerHTML=emptyPanel;panelIn()}
const pHead=$('pHead');
const pBody=document.createElement('div');pBody.id='pBody';
while(pHead.nextSibling&&pHead.nextSibling.id!=='chat')pBody.appendChild(pHead.nextSibling);
panel.insertBefore(pBody,$('chat'));
const emptyPanel=pBody.innerHTML;
function esc(s){return String(s==null?'':s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function kindName(k){return {owns:'owns',refs:'references',poly:'polymorphic',view:'derived',actor:'actor',self:'self'}[k]}
function renderPanel(name,viaEdge){
  const e=E[name];
  const inc=edges.filter(ed=>ed.t===name&&edgeVisible(ed)&&ed.s!==name);
  const out=edges.filter(ed=>ed.s===name&&edgeVisible(ed)&&ed.t!==name);
  const self=edges.filter(ed=>ed.s===name&&ed.t===name);
  const invs=INV.filter(i=>i[0].includes(name));
  const rel=(list,dir)=>list.length?`<ul class="rel">${list.map(ed=>{const other=dir==='in'?ed.s:ed.t;
    return `<li><button class="ent" data-go="${other}">${other}</button><div class="how">${esc(ed.label)}<span class="kindtag ${ed.k}">${kindName(ed.k)}</span><small>${esc(ed.card)}${ed.fk?' · '+esc(ed.fk):''}</small></div></li>`}).join('')}</ul>`:'<p class="empty">none</p>';
  const lockbar=state.walk===null&&!state.trace?(state.sel===name?`<div class="lockbar locked">Locked · click the entity again to unlock</div>`:`<div class="lockbar">Preview · click the entity to lock</div>`):'';
  pBody.innerHTML=`
    ${lockbar}
    <h2>${name}</h2>
    <div class="dom"><i style="background:${DOMS[e.d].c}"></i>${DOMS[e.d].name}</div>
    <p>${esc(e.desc)}</p>
    ${viaEdge?`<p class="empty">Via edge: <strong>${esc(viaEdge.s)} → ${esc(viaEdge.t)}</strong>, ${esc(viaEdge.label)} (${esc(viaEdge.card)}).</p>`:''}
    <div class="acts">
      <button class="btn" data-trace="down">${IC.branch}Trace downstream</button>
      <button class="btn" data-trace="up">${IC.branch}Trace upstream</button>
      <button class="btn" data-center="1">${IC.fit}Fit to connections</button>
      ${cfg.flaggingEnabled?`<button class="btn" data-flag="1">Flag this entity</button>`:''}
    </div>
    <div class="flagbox" id="flagbox" hidden></div>
    <h3>Fed by · upstream (${inc.length})</h3>${rel(inc,'in')}
    <h3>Feeds · downstream (${out.length})</h3>${rel(out,'out')}
    ${self.length?`<h3>Self reference</h3><ul class="rel">${self.map(ed=>`<li><button class="ent" data-go="${name}">${name}</button><div class="how">${esc(ed.label)}<span class="kindtag self">self</span><small>${esc(ed.card)} · ${esc(ed.fk)}</small></div></li>`).join('')}</ul>`:''}
    ${invs.length?`<h3>Invariants</h3><ul class="inv">${invs.map(i=>`<li>${esc(i[1])}</li>`).join('')}</ul>`:''}
    <h3>${e.d==='view'?'Parameters':'Fields ('+e.f.length+')'}</h3>
    <table class="fields">${e.f.map(r=>`<tr><td class="n">${esc(r[0])}</td><td class="t">${esc(r[1])}</td><td class="k">${esc(r[2]||'')}</td><td class="o">${esc(r[3]||'')}</td></tr>`).join('')}</table>`;
  panel.scrollTop=0;panelIn();
  pBody.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>select(b.dataset.go,null,{force:true})));
  pBody.querySelectorAll('[data-trace]').forEach(b=>b.addEventListener('click',()=>trace(name,b.dataset.trace)));
  pBody.querySelector('[data-center]').addEventListener('click',()=>fitTo([name,...neighbours(name)]));
  const fb=pBody.querySelector('[data-flag]');if(fb)fb.addEventListener('click',()=>openFlag(name));
}
function trace(name,dir){
  const ns=new Set([name]),es=new Set();const queue=[name];
  while(queue.length){const cur=queue.shift();edges.forEach(ed=>{if(!edgeVisible(ed)||ed.k==='actor')return;
    const from=dir==='down'?ed.s:ed.t,to=dir==='down'?ed.t:ed.s;
    if(from===cur&&!es.has(ed)){es.add(ed);if(!ns.has(to)){ns.add(to);queue.push(to)}}})}
  state.trace={nodes:ns,edges:es};state.sel=name;applyHighlight();fitTo([...ns]);cfg.onEvent&&cfg.onEvent('trace',{entity:name,dir,reach:ns.size-1});
  const h=pBody.querySelector('h2');
  let note=pBody.querySelector('.tracenote');
  if(!note){note=document.createElement('p');note.className='tracenote empty';h.after(note)}
  note.textContent=`${dir==='down'?'Downstream':'Upstream'} reach: ${ns.size-1} entities over ${es.size} links. Click Clear or another entity to reset.`;
}

/* ------------------------------------------------------------------ walkthroughs */
const walkSel=$('walkSel'),walkBar=$('walk'),wPos=$('wPos'),wTxt=$('wTxt'),wBar=walkBar.querySelector('.bar');
WALKS.forEach((w,i)=>{const o=document.createElement('option');o.value=i;o.textContent=w.name;walkSel.appendChild(o)});
walkSel.addEventListener('change',()=>{if(walkSel.value==='')exitWalk();else startWalk(+walkSel.value)});
function startWalk(i){state.walk=i;state.step=0;state.sel=null;state.trace=null;walkBar.classList.add('on');walkSel.classList.add('on');showStep();cfg.onEvent&&cfg.onEvent('walkthrough',{name:WALKS[i].name})}
function showStep(){const w=WALKS[state.walk],s=w.steps[state.step];
  wPos.innerHTML=`<b>${esc(w.name)}</b><span>step ${state.step+1} of ${w.steps.length}</span>`;
  wTxt.innerHTML=`<b>${s[0]}</b> — ${esc(s[1])}`;
  wBar.style.width=((state.step+1)/w.steps.length*100)+'%';
  wTxt.classList.remove('in');void wTxt.offsetWidth;wTxt.classList.add('in');
  $('wPrev').disabled=state.step===0;
  $('wNext').innerHTML=state.step===w.steps.length-1?'Done':`Next ${IC.right}`;
  applyHighlight();renderPanel(s[0]);pulse(s[0]);fitTo(state.step>0?[w.steps[state.step-1][0],s[0]]:[s[0]]);}
function exitWalk(){state.walk=null;walkBar.classList.remove('on');walkSel.classList.remove('on');walkSel.value='';applyHighlight()}
$('wPrev').addEventListener('click',()=>{if(state.step>0){state.step--;showStep()}});
$('wNext').addEventListener('click',()=>{const w=WALKS[state.walk];if(state.step<w.steps.length-1){state.step++;showStep()}else exitWalk()});
$('wExit').addEventListener('click',exitWalk);

/* ------------------------------------------------------------------ pan / zoom */
const stage=$('stage');
let vt={x:0,y:0,k:1};
let vtAnim=null;
function applyVT(){world.setAttribute('transform',`translate(${vt.x},${vt.y}) scale(${vt.k})`)}
function stopTween(){if(vtAnim){vtAnim.pause();vtAnim=null}}
function goTo(target,instant,ms){
  stopTween();
  if(instant||RM){Object.assign(vt,target);applyVT();return}
  moving();
  vtAnim=animate(vt,{x:target.x,y:target.y,k:target.k,duration:ms||480,ease:'outQuart',onUpdate:()=>{moving();applyVT()},onComplete:()=>{vtAnim=null}});
}
function bounds(){let x1=1e9,y1=1e9,x2=-1e9,y2=-1e9;for(const n in nodes){const o=nodes[n];if(o.g.style.display==='none')continue;x1=Math.min(x1,o.x);y1=Math.min(y1,o.y);x2=Math.max(x2,o.x+o.w);y2=Math.max(y2,o.y+o.h)}return {x1:x1-40,y1:y1-60,x2:x2+40,y2:y2+40}}
let needFit=false;
function fit(instant){const b=bounds(),r=stage.getBoundingClientRect();
  if(!(r.width>0&&r.height>0)){needFit=true;return}            // stage not laid out yet: the ResizeObserver will call back
  const k=Math.min(r.width/(b.x2-b.x1),r.height/(b.y2-b.y1));
  if(!isFinite(k)||k<=0)return;
  goTo({k,x:(r.width-(b.x2-b.x1)*k)/2-b.x1*k,y:(r.height-(b.y2-b.y1)*k)/2-b.y1*k},instant)}
function fitTo(names,instant){const vis=names.filter(n=>nodes[n]&&nodes[n].g.style.display!=='none');if(!vis.length)return;
  let x1=1e9,y1=1e9,x2=-1e9,y2=-1e9;vis.forEach(n=>{const o=nodes[n];x1=Math.min(x1,o.x);y1=Math.min(y1,o.y);x2=Math.max(x2,o.x+o.w);y2=Math.max(y2,o.y+o.h)});
  const r=stage.getBoundingClientRect(),pad=60;if(!(r.width>0&&r.height>0)){needFit=true;return}
  const k=Math.max(0.12,Math.min(1.15,(r.width-pad*2)/(x2-x1),(r.height-pad*2)/(y2-y1)));
  goTo({k,x:(r.width-(x2-x1)*k)/2-x1*k,y:(r.height-(y2-y1)*k)/2-y1*k},instant)}
function zoomAt(f,cx,cy){stopTween();const nk=Math.min(3,Math.max(0.12,vt.k*f));vt.x=cx-(cx-vt.x)*(nk/vt.k);vt.y=cy-(cy-vt.y)*(nk/vt.k);vt.k=nk;applyVT()}
function zoomButton(f){const r=stage.getBoundingClientRect(),cx=r.width/2,cy=r.height/2;const nk=Math.min(3,Math.max(0.12,vt.k*f));goTo({k:nk,x:cx-(cx-vt.x)*(nk/vt.k),y:cy-(cy-vt.y)*(nk/vt.k)},false,280)}
let movingTimer=null,raf=0,pendingWheel=null,pendingPan=null;
function moving(){svg.classList.add('moving');clearTimeout(movingTimer);movingTimer=setTimeout(()=>svg.classList.remove('moving'),160)}
cleanups.push(()=>clearTimeout(movingTimer));
function flush(){raf=0;
  if(pendingWheel){const {f,cx,cy}=pendingWheel;pendingWheel=null;zoomAt(f,cx,cy)}
  if(pendingPan){vt.x=pendingPan.x;vt.y=pendingPan.y;pendingPan=null;applyVT()}}
function schedule(){if(!raf)raf=requestAnimationFrame(flush)}
stage.addEventListener('wheel',ev=>{ev.preventDefault();moving();const r=stage.getBoundingClientRect();const f=Math.exp(-ev.deltaY*(ev.ctrlKey?0.01:0.002));
  pendingWheel={f:(pendingWheel?pendingWheel.f*f:f),cx:ev.clientX-r.left,cy:ev.clientY-r.top};schedule()},{passive:false});
let drag=null;
const hint=$('hint');
function byeHint(){hint.classList.add('bye')}
const hintTimer=setTimeout(byeHint,9000);cleanups.push(()=>clearTimeout(hintTimer));
svg.addEventListener('pointerdown',ev=>{if(ev.button!==0&&ev.pointerType==='mouse')return;stopTween();drag={x:ev.clientX,y:ev.clientY,vx:vt.x,vy:vt.y,moved:false,onNode:!!(ev.target.closest&&ev.target.closest('.node,.edge-hit')),id:ev.pointerId}});
svg.addEventListener('pointermove',ev=>{if(!drag)return;const dx=ev.clientX-drag.x,dy=ev.clientY-drag.y;if(!drag.moved&&Math.abs(dx)+Math.abs(dy)>4){drag.moved=true;byeHint();try{svg.setPointerCapture(drag.id)}catch(e){}svg.classList.add('panning')}if(!drag.moved)return;moving();pendingPan={x:drag.vx+dx,y:drag.vy+dy};schedule()});
svg.addEventListener('pointerup',ev=>{if(drag&&!drag.moved&&!drag.onNode){/* click on empty canvas: unlock */ if(state.walk===null){state.sel=null;state.trace=null;state.hover=null;previewed=null;applyHighlight();pBody.innerHTML=emptyPanel;panelIn()}}try{svg.releasePointerCapture(ev.pointerId)}catch(e){}drag=null;svg.classList.remove('panning')});
svg.addEventListener('pointercancel',()=>{drag=null;svg.classList.remove('panning')});
$('zIn').addEventListener('click',()=>zoomButton(1.5));
$('zOut').addEventListener('click',()=>zoomButton(1/1.5));
$('zFit').addEventListener('click',()=>fit());
$('bFit').addEventListener('click',()=>fit());
$('bClear').addEventListener('click',()=>{$('q').value='';state.q='';clearAll();fit()});
// Keep the view sensible when the stage changes size (panel collapse, window resize, first layout).
let rsTimer=null,hadSize=false;
const ro=new ResizeObserver(()=>{const r=stage.getBoundingClientRect();const has=r.width>0&&r.height>0;
  if(has&&(!hadSize||needFit)){hadSize=true;needFit=false;fit(true);return}
  if(!has)return;
  clearTimeout(rsTimer);rsTimer=setTimeout(()=>{if(state.walk!==null)return;if(state.trace)fitTo([...state.trace.nodes]);else if(state.sel)fitTo([state.sel,...neighbours(state.sel)]);else fit()},90)});
ro.observe(stage);cleanups.push(()=>{ro.disconnect();clearTimeout(rsTimer)});
const legend=$('legend');
$('legTog').addEventListener('click',()=>{const mini=legend.classList.toggle('mini');$('legTog').textContent=mini?'show':'hide';try{localStorage.setItem('erd-legend',mini?'0':'1')}catch(e){}});
try{if(localStorage.getItem('erd-legend')==='0'){legend.classList.add('mini');$('legTog').textContent='show'}}catch(e){}

/* ------------------------------------------------------------------ controls */
const bView=$('bView'),viewPop=$('viewPop'),viewCount=$('viewCount');
root.style.position='relative';root.appendChild(viewPop);                    // out of the scrolling toolbar so it is never clipped
function setPop(open){viewPop.hidden=!open;bView.setAttribute('aria-expanded',open?'true':'false');bView.classList.toggle('on',open);
  if(open){const b=bView.getBoundingClientRect(),r=root.getBoundingClientRect();viewPop.style.top=(b.bottom-r.top+8)+'px';viewPop.style.right=Math.max(12,r.right-b.right)+'px';viewPop.style.left='';
    if(viewPop.offsetWidth>r.width-24){viewPop.style.left='12px';viewPop.style.right='12px'}}}
bView.addEventListener('click',ev=>{ev.stopPropagation();setPop(viewPop.hidden)});
const onDocClick=ev=>{if(!viewPop.hidden&&!viewPop.contains(ev.target)&&ev.target!==bView&&!bView.contains(ev.target))setPop(false)};
document.addEventListener('pointerdown',onDocClick);cleanups.push(()=>document.removeEventListener('pointerdown',onDocClick));
function updateViewCount(){const d=[tAll.checked,tLbl.checked,tActor.checked,!tPoly.checked,!tView.checked].filter(Boolean).length;viewCount.textContent=d?String(d):'';viewCount.hidden=!d}
const tAll=$('tAll');[tAll,tLbl,tActor,tPoly,tView].forEach(t=>t.addEventListener('change',updateViewCount));updateViewCount();
const chips=$('domchips'),legdoms=$('legdoms');
for(const d in DOMS){const b=document.createElement('button');b.className='chip';b.type='button';b.innerHTML=`<i style="background:${DOMS[d].c}"></i>${DOMS[d].name}`;b.title='Toggle focus on this domain';
  b.addEventListener('click',()=>{if(state.domOff.has(d))state.domOff.delete(d);else state.domOff.add(d);b.classList.toggle('off',state.domOff.has(d));applyHighlight()});chips.appendChild(b);
  const s=document.createElement('span');s.innerHTML=`<i style="background:${DOMS[d].c}"></i>${DOMS[d].name}`;legdoms.appendChild(s)}
tAll.addEventListener('change',ev=>{showAll=ev.target.checked;rebuild()});
[tActor,tPoly,tView].forEach(t=>t.addEventListener('change',()=>{applyVisibility();applyHighlight();if(state.sel)renderPanel(state.sel)}));
tLbl.addEventListener('change',applyHighlight);
const q=$('q');
q.addEventListener('input',()=>{state.q=q.value.trim().toLowerCase();applyHighlight()});
q.addEventListener('keydown',ev=>{if(ev.key==='Enter'&&state.q){const hit=Object.keys(E).find(n=>matches(n,state.q));cfg.onEvent&&cfg.onEvent('search',{query:state.q,hit:hit||null});if(hit)select(hit,null,{force:true})}
  if(ev.key==='Escape'){q.value='';state.q='';applyHighlight();q.blur()}});
function rebuild(){const sel=state.sel;build();if(sel){state.sel=sel;applyHighlight()}}
const onKey=ev=>{const t=ev.target;const typing=t&&(t.tagName==='INPUT'||t.tagName==='TEXTAREA'||t.tagName==='SELECT'||t.isContentEditable);
  if(ev.key==='/'&&!typing){ev.preventDefault();q.focus();q.select();return}
  if(ev.key==='Escape'&&!typing){if(!viewPop.hidden)setPop(false);else if(state.walk!==null)exitWalk();else if(state.sel||state.trace){state.sel=null;state.trace=null;applyHighlight();if(previewed)renderPanel(previewed,null)}return}
  if(state.walk!==null&&!typing){if(ev.key==='ArrowRight'){$('wNext').click()}else if(ev.key==='ArrowLeft'){$('wPrev').click()}}};
document.addEventListener('keydown',onKey);cleanups.push(()=>document.removeEventListener('keydown',onKey));

build();
fit(true);
intro();

/* ------------------------------------------------------------------ panel tabs */
const chatEl=$('chat');
const oqEl=$('oq');
const ink=pHead.querySelector('.ink');
function moveInk(){const on=pHead.querySelector('.ptab.on');if(!on)return;ink.style.left=on.offsetLeft+'px';ink.style.width=on.offsetWidth+'px'}
function setTab(t){pHead.querySelectorAll('.ptab').forEach(b=>b.classList.toggle('on',b.dataset.tab===t));pBody.hidden=t!=='details';chatEl.hidden=t!=='ask';oqEl.hidden=t!=='oq';if(t!=='details')setPanel(true);moveInk();if(t==='ask')setTimeout(()=>chatIn.focus(),50);cfg.onEvent&&cfg.onEvent('tab',{tab:t})}
moveInk();if(document.fonts&&document.fonts.ready)document.fonts.ready.then(moveInk);
const inkRo=new ResizeObserver(moveInk);inkRo.observe(pHead);cleanups.push(()=>inkRo.disconnect());
(function renderOQ(){const n={answered:0,open:0,pending:0};OPENQ.forEach(q=>n[q.status]++);n.gap=SCENARIOS.length;
  oqEl.innerHTML=`<p class="intro">The 13 open questions carried from the Understanding document plus 6 review points from the reviews of 6–8 October 2026 — the last, the PARTNER_ENTITY rename, pending NPL confirmation. Each shows the recorded answer (Sud’s comment or the review) and how the current draft reflects it. Entities marked NEW or CHANGED on the map come from these decisions.</p>
  <div class="sum"><span class="st answered">${n.answered} answered</span><span class="st open">${n.open} to be discussed</span><span class="st pending">${n.pending} pending</span><span class="st gap">${n.gap} scenarios, resolved in v4.0</span></div>`+
  OPENQ.map((q,i)=>`<div class="oqi" style="animation-delay:${Math.min(i,12)*40}ms"><div class="h"><span class="num">Q${i+1}</span><div><div class="qt">${esc(q.q)}</div><div class="blk">blocks: ${esc(q.blocks)}</div></div><span class="st ${q.status}">${q.status==='answered'?'answered':q.status==='pending'?'pending':'to discuss'}</span></div>
   <p class="ans"><b>Sud:</b> ${esc(q.a)}</p><p class="impl">${esc(q.impl)}</p>
   <div class="ents">${q.ents.map(e=>`<button type="button" class="ent" data-ent="${e}">${e}</button>`).join('')}<button type="button" class="askq" data-askq="${i}">Ask the bot ↗</button></div></div>`).join('')+
  `<h3 style="font-size:10.5px;letter-spacing:.09em;text-transform:uppercase;color:var(--muted);margin:18px 0 6px;font-weight:650">Edge-case scenarios</h3><p class="intro">Scenarios traced step by step against ERD v3.0 in the review of 6–7 October 2026, and how the current draft resolves each (v4.0 resolutions, unchanged since). The traces are analysis, not source text.</p>`+
  SCENARIOS.map((sc,i)=>`<div class="oqi"><div class="h"><span class="num">${sc.id}</span><div><div class="qt">${esc(sc.name)}</div></div><span class="st answered">resolved in v4.0</span></div>
   <p class="ans">${esc(sc.story)}</p>
   <ol class="trace">${sc.trace.map(t=>`<li><b>${esc(t[0])}.</b> ${esc(t[1])}</li>`).join('')}</ol>
   <p class="ans"><b>v3.0 verdict:</b> ${esc(sc.verdict)}</p><p class="ans"><b>v4.0:</b> ${esc(SCENARIO_V4[sc.id]||'')}</p>
   <div class="ents">${sc.ents.map(e=>`<button type="button" class="ent" data-ent="${e}">${e}</button>`).join('')}<button type="button" class="askq" data-asks="${i}">Ask the bot ↗</button></div></div>`).join('');
  oqEl.addEventListener('click',ev=>{const b=ev.target.closest('[data-ent]');if(b){select(b.dataset.ent,null,{stayTab:true});return}
    const a=ev.target.closest('[data-askq]');if(a){const q=OPENQ[+a.dataset.askq];setTab('ask');chatIn.value=`Open question ${+a.dataset.askq+1}: ${q.q}. What is the recorded answer, what is its status, and how does the current draft reflect it?`;ask();return}
    const sc=ev.target.closest('[data-asks]');if(sc){const x=SCENARIOS[+sc.dataset.asks];setTab('ask');chatIn.value=`Scenario ${x.id}: ${x.name}. Why did ERD v3.0 fail it, step by step, and how does the current draft handle it?`;ask()}});
})();
pHead.querySelectorAll('.ptab').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));


/* ------------------------------------------------------------------ flagging */
function openFlag(name){const box=$('flagbox');if(!box)return;box.hidden=false;
  box.innerHTML=`<label style="font-size:12px">Flag <strong>${esc(name)}</strong>: what is wrong or missing?</label><textarea id="flagTxt" placeholder="e.g. receiving entity accounts also need a holder name"></textarea><div class="row"><button class="btn ghost" id="flagCancel" type="button">Cancel</button><button class="btn primary" id="flagSend" type="button">Send flag</button></div>`;
  box.querySelector('#flagTxt').focus();
  box.querySelector('#flagCancel').addEventListener('click',()=>{box.hidden=true});
  box.querySelector('#flagSend').addEventListener('click',async()=>{const t=box.querySelector('#flagTxt').value.trim();if(!t)return;
    const b=box.querySelector('#flagSend');b.disabled=true;
    try{const r=await fetch(cfg.flagsUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({entity:name,comment:t})});
      box.innerHTML=r.ok?`<span class="ok">Flag recorded. Thank you.</span>`:`<span style="color:var(--hi)">Could not record the flag (${r.status}).</span>`}
    catch(e){box.innerHTML=`<span style="color:var(--hi)">Could not record the flag.</span>`}});
}

/* ------------------------------------------------------------------ chat (server-backed) */
const chatLog=$('chatLog'),chatIn=$('chatIn'),chatForm=$('chatForm'),chatSend=$('chatSend'),chatStop=$('chatStop'),chatSug=$('chatSug'),chatNote=$('chatNote');
const SUGGEST=['How does a BF Sub deal via Aquanow work end to end, and where does the Aquanow rebate go?','Which projects belong to the Betfair client, and how do I see the client-level balance?','How does a GDC transaction that crosses USD 500,000 in a month get priced?','What happens when a one-time local deposit account is frozen after the deposit?','How does the 14:30 cutoff change a deal collected in the evening?','What changed in v5.3 and v5.4, and which NPL fee practice does each decision come from?','How does money flow from a collection to the receiver’s confirmation?','What must exist before a quote-first deal can leave Inquiry?','What is a receiver group and when do offsets arise?','How is a rejected payout handled?','How does a two-leg route across two partners work?','Which figures are never stored, and how is each computed?','What changes on a reroute, and what stays fixed?','When is a partner rate version breached, and what happens then?','List every entity that hangs off PARTNER_CONFIG.','Which open questions are still unresolved?'];
(cfg.visitor?SUGGEST.filter(q=>!/v5\.|open question/i.test(q)):SUGGEST).forEach((q,i)=>{const b=document.createElement('button');b.type='button';b.textContent=q;b.style.animationDelay=(i*25)+'ms';b.addEventListener('click',()=>{chatIn.value=q;ask()});chatSug.appendChild(b)});
let turns=[],ctl=null,busy=false,sessionId=cfg.sessionId||(crypto.randomUUID?crypto.randomUUID():String(Date.now()));
const ENT_RE=new RegExp('\\b('+Object.keys(E).sort((a,b)=>b.length-a.length).join('|')+')\\b','g');
function md(t){
  let h=esc(t).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
  const lines=h.split('\n'),out=[];let list=null;
  const flush=()=>{if(list){out.push(`<${list.t}>${list.items.map(i=>'<li>'+i+'</li>').join('')}</${list.t}>`);list=null}};
  for(let ln of lines){const m=ln.match(/^\s*([-*•]|\d+[.)])\s+(.*)$/);
    if(m){const t=/^\d/.test(m[1])?'ol':'ul';if(!list||list.t!==t){flush();list={t,items:[]}}list.items.push(m[2]);continue}
    flush();const hm=ln.match(/^#{1,4}\s+(.*)$/);if(hm){out.push('<h4>'+hm[1]+'</h4>');continue}
    if(ln.trim())out.push('<p>'+ln+'</p>')}
  flush();
  return out.join('').replace(ENT_RE,(m)=>`<button type="button" class="ent" data-ent="${m}">${m}</button>`);
}
function splitMap(text){const m=text.match(/\[\[map:\s*([^\]]*)\]\]\s*$/);if(!m)return {body:text,ents:[]};
  const ents=m[1].split(/[,\s]+/).map(x=>x.trim()).filter(x=>E[x]);return {body:text.slice(0,m.index).trimEnd(),ents:[...new Set(ents)]}}
function addMsg(cls,text){const d=document.createElement('div');d.className='msg '+cls;
  if(cls==='user')d.textContent=text;
  else if(cls.includes('thinking'))d.innerHTML=`<span class="dots"><i></i><i></i><i></i></span><span>${esc(text)}</span>`;
  else d.innerHTML=md(text);
  chatLog.appendChild(d);chatLog.scrollTop=chatLog.scrollHeight;return d}
function renderBot(d,text,final,msgId){const {body,ents}=splitMap(text);d.innerHTML=md(final?body:body.replace(/\[\[map:[^\]]*$/,''));
  if(final){
    if(ents.length){const row=document.createElement('div');row.className='entrow';row.innerHTML='<span style="color:var(--muted);font-size:11px">On the map:</span>'+ents.map(e=>`<button type="button" class="ent" data-ent="${e}">${e}</button>`).join('');d.appendChild(row);
      state.sel=null;state.trace={nodes:new Set(ents),edges:new Set(edges.filter(ed=>ents.includes(ed.s)&&ents.includes(ed.t)&&edgeVisible(ed)))};applyHighlight();fitTo(ents)}
    if(msgId){const fb=document.createElement('div');fb.className='fb';fb.innerHTML='<button type="button" data-fb="up" title="Helpful">👍</button><button type="button" data-fb="down" title="Not helpful">👎</button>';d.appendChild(fb);
      fb.addEventListener('click',ev=>{const b=ev.target.closest('[data-fb]');if(!b)return;fb.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));
        fetch(cfg.feedbackUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messageId:msgId,feedback:b.dataset.fb})}).catch(()=>{})})}
  }
  chatLog.scrollTop=chatLog.scrollHeight}
chatLog.addEventListener('click',ev=>{const b=ev.target.closest('[data-ent]');if(b){select(b.dataset.ent,null,{stayTab:true,force:true})}});
async function ask(){const q=chatIn.value.trim();if(!q||busy)return;chatIn.value='';chatSug.hidden=true;addMsg('user',q);
  busy=true;chatSend.disabled=true;chatStop.hidden=false;const d=addMsg('bot thinking','Thinking…');
  turns.push({role:'user',content:q});while(turns.length>14)turns.shift();
  ctl=new AbortController();let text='';
  try{
    const r=await fetch(cfg.askUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sessionId,messages:turns}),signal:ctl.signal});
    if(!r.ok){const err=await r.text().catch(()=>'');throw new Error(r.status===429?'You have reached today’s question limit. Try again tomorrow.':r.status===401?'Your session has expired. Reload the page to sign in again.':(err||('Request failed ('+r.status+')')))}
    const msgId=r.headers.get('x-message-id');
    const reader=r.body.getReader(),dec=new TextDecoder();
    while(true){const {value,done}=await reader.read();if(done)break;text+=dec.decode(value,{stream:true});d.className='msg bot';renderBot(d,text,false)}
    d.className='msg bot';renderBot(d,text,true,msgId);turns.push({role:'assistant',content:text});
  }catch(e){
    if(e.name==='AbortError'){if(text){d.className='msg bot';renderBot(d,text,true);turns.push({role:'assistant',content:text})}else{d.remove();turns.pop()}}
    else{if(text){d.className='msg bot';renderBot(d,text,true)}else{d.remove();turns.pop()}addMsg('bot err',e.message||'The assistant did not answer. Try again.')}
  }finally{busy=false;chatSend.disabled=false;chatStop.hidden=true;ctl=null}}
chatForm.addEventListener('submit',ev=>{ev.preventDefault();ask()});
chatIn.addEventListener('keydown',ev=>{if(ev.key==='Enter'&&!ev.shiftKey){ev.preventDefault();ask()}});
chatStop.addEventListener('click',()=>{if(ctl)ctl.abort()});
$('chatClear').addEventListener('click',()=>{if(ctl)ctl.abort();turns=[];chatLog.innerHTML='';chatSug.hidden=false;sessionId=crypto.randomUUID?crypto.randomUUID():String(Date.now())});

return {destroy(){stopTween();cleanups.forEach(f=>{try{f()}catch(e){}});root.innerHTML='';}, select, fit};
}
