#!/usr/bin/env python3
"""Add the scenario catalogue (projects → scenarios → ERD path, shared flows F1–F10, open questions) to
data/erd.v5.json as SCENARIO_CATALOGUE, the assistant's fifth source. Content mirrors the 'NPLify Scenario
Catalogue v1.0' doc of 9 October 2026, in v5.4 names. Idempotent.   python3 scripts/apply-v5.4-scenarios.py"""
import json
from pathlib import Path

P = Path(__file__).resolve().parent.parent / "data/erd.v5.json"
d = json.loads(P.read_text())
assert d["version"] == "5.4"

PROJECTS = [
 {"client": "Betfair (BF)", "projects": "BF, BF Sub, BF Withdrawal — three PROJECTs of one CLIENT (D38); client-level balances and earnings from CLIENT_POSITION", "lead": "Betfair customers fund their accounts in USDT converted to EUR; three partners, three fee mechanics, one withdrawal route back. Aquanow is used for everything today, Jeton is inactive, Ali is the alternative.", "scenarios": [
  ["BF via Jeton: market minus fee, rebate back", "Sender (Seven, Arrow Wood, Trade Lab, Orbit, Blue Sapphire) pays 1 % off market; Jeton keeps the full 1 % and pays NPL 0.4 % back monthly; Novi pays 0.9 % with 0.3 % back", "Fixed fee on market basis; F2 in, F5 out to BF's Sporting Exchange account", "FEE_STRUCTURE (rate_basis market); FEE_OVERRIDE for Novi; PARTNER_REBATE_RULE 0.4 % of amount, scoped 0.3 % for Novi; PARTNER_REBATE_ACCRUAL reconciled against Jeton's statement; income in EARN_REBATE (D27)"],
  ["BF via Ali: agent rate, customer-facing 1 %", "Ali's 1 % sits inside its rate, NPL adds 0.4 %, the customer's calculation shows 'fee 1 %' on a recomputed source rate; Ali sometimes quotes 1.1738 the other way round", "Fixed fee on agent-rate basis; F2 in, F4/F5 by SWIFT under PT Sukses, F9 cutoff on the EUR settlement", "customer_facing_fee_basis fixed 1 % on FEE_STRUCTURE, customer_facing_rate on DEAL_GROUP (D22); quoted_rate and quoted_direction on PARTNER_RATE_VERSION (D28); QUOTE_PACKAGE keeps the printed figures (D35)"],
  ["BF via Aquanow: flat 0.8 %, rebate 0.3 %", "Aquanow charges 0.8 % and pays NPL 0.3 % back monthly; EUR reaches BF by internal transfer, instantly", "Fixed fee; F2 in, F10 out", "PARTNER_PAIR fee_on_market with partner_fee_pct 0.8 %; PARTNER_REBATE_RULE 0.3 % of amount; RECEIVING_ENTITY_ACCOUNT.rail internal (D18)"],
  ["BF Sub via Aquanow or Ali: markup shared with Raeen", "Downlines fund a sub-account Raeen provides at 4 %; the 4 % less the partner fee (3.2 % via Aquanow, 3 % via Ali) is split equally with Raeen; the EUR lands in Raeen's own Aquanow account, Raeen keeps its share and pays NPL monthly; Aquanow's 0.3 % rebate is NPL's alone; direct downlines: 1 %, the 0.2 % left split 75/25", "Fixed 4 % with a share rule; F2 in, F10 out (Aquanow) or F5 under Raeen's name (Ali)", "MARKUP_SHARE_RULE basis share_of_net_markup, party_kind client_party, settlement_mode party_retains, scoped by fee structure; MARKUP_SHARE_ACCRUAL as a receivable in SHARE_RECEIVABLE (D26); rebate outside the base (D27); SETTLEMENT_SENDING_ENTITY Raeen on the Ali route"],
  ["BF Withdrawal via Jeton", "BF wires the customer's balance to Jeton's SWIFT account; Jeton converts at 1 % over market and pays the customer's TRC-20 or ERC-20 wallet; 0.4 % back monthly; Jeton is the only partner able to receive it", "Fixed 1 %; F4 in (bank at Jeton), F3 then wallet payout", "Bank endpoint with rail (D18); RECEIVING_ENTITY_ACCOUNT kind wallet (D14); DESTINATION_APPROVAL with network and address (D16); WALLET_SCREENING on the receiver wallet (D31); rebate as above"]]},
 {"client": "Evo", "projects": "Evo", "lead": "Evo's customers pay their invoices to Evo through NPL; everything converts into EUR; two receiver groups with senders designated per group; Ali and Jeton can each pay only some entities.", "scenarios": [
  ["Standard USDT collection", "Sender pays 1.4 % off the rate, Evo pays 0.6 % from its balance at conversion; sender sees only the sender rate", "2 % split 1.4 / 0.6; F2 in (screening not done for every Evo sender), F5 out by SWIFT under Bplay", "FEE_STRUCTURE sender_pays_pct / receiver_pays_pct; CONVERSION.fee_receiver_part; COLLECTION.screening_skipped (D31)"],
  ["Selected senders (GTSI, HG, Komodo)", "Sender pays 1.0 % while Evo still pays 0.6 %", "1.6 % with the receiver part fixed", "FEE_OVERRIDE with its own sender_pays_pct and receiver_pays_pct (D20); DEAL.fee_override_id"],
  ["Two receiver groups", "Bplay (Babylon on an invoice reference, Bplay and Lex as self-transfers) and TBet; Ali pays Babylon and TBet, Jeton pays Bplay, Lex and TBet", "Configuration", "RECEIVER_GROUP, SENDER_RECEIVER_ALLOW per sender, DESTINATION_APPROVAL per entity per partner; invariant 8"],
  ["Collect-first and quote-first senders", "Some pay what they can, others the exact invoice", "Entry mode per sender", "DEAL_GROUP.entry_mode collect_first / quote_first"],
  ["Via Jeton instead of Ali", "Jeton charges 1.25 % overall and pays 0.4 % back monthly; Jeton collects USDT only", "F2 in, F5 out", "PARTNER_PAIR fee_on_market with partner_fee_pct 1.25 %; PARTNER_REBATE_RULE 0.4 % of amount (D27)"],
  ["Other currencies via Ali, and the 14:30 cutoff", "Rate taken from Ali in the morning and compared; a deal locked before 14:30 GMT+8 converts the same day, after it the collection goes ahead on the morning's figures and converts the next business day; NPL absorbs the difference; an unacceptable next-day rate is renegotiated or deferred a day", "F4 in, F9", "PARTNER.bank_cutoff_time, PARTNER_CUTOFF_OVERRIDE, HOLIDAY (D29, D34); DEAL.rate_locked_at, cutoff_at, conversion_due_date, conversion_deferred_reason; cutoff_timing variance; pending value in PROJECT_BALANCE"],
  ["Returned payout", "A bank rejects the transfer", "F6", "SETTLEMENT_RETURN, reversing posting, return leg to the sender_return receiver (D13)"]]},
 {"client": "NPL-GR (Game Reseller)", "projects": "Game Reseller — NPL's own business unit as the client, run as an own-desk project (D23, D38)", "lead": "NPL resells games at retail against wholesale vendor invoices and collects its receivables to pay the vendors; Management confirmed running it inside NPLify as an own-desk project.", "scenarios": [
  ["USDT customers (Bala, Fair, 66 Group GR, TripleSeven, Alpha Plus)", "Customer owes EUR, pays USDT straight into NPL's own wallet (LT Sub at Aquanow, occasionally Ali's wallet as NPL's own balance); 2 % markup over market; the USDT collected is rounded up", "Fixed 2 % (0.75-1.5 % for some); F2 in to NPL's wallet", "CLIENT NPL-GR with its PROJECT (D38); PARTNER_CONFIG.is_own_desk; OWN_WALLET as COLLECTION_RECEIVING_ENDPOINT; invariant 3 restated (D23); CURRENCY_PAIR round_up_unit (D25)"],
  ["27 Group: THB cash", "Customer pays THB cash by token through Ali at market + 2 %; Ali converts THB to USDT, which moves to NPL's wallet or stays at Ali as NPL's balance; Ali's rate must stay within 1.5 % of market so NPL keeps 0.5 %", "Fixed 2 %; F1 in; INR cash possible later by the same process", "DEAL.cash_location, COLLECTION.token_ref, counted_at (D30); PARTNER_RATE_VERSION breach threshold 1.5 % warning Finance; min_margin_pct 0.5 %"],
  ["Vendor invoices paid in parts", "Customers pay against a EUR invoice or an advance; vendors (SACCO SIA, Mitratech, EZ-EVO, BraversPlay) are paid in USDT on different days at that day's rate; the forex difference is accepted within the 2 %", "USDT settlements to vendor wallets, F3 before each", "INVOICE under PROJECT; DEAL_GROUP.invoice_id; SETTLEMENT_LINE.obligation_discharged, discharge_rate, discharge_market_rate_id; INVOICE_BALANCE view; fx_timing variance (D24)"]]},
 {"client": "YN Remit, 66 Group, GDC, Peru (invoice-payment projects)", "projects": "one PROJECT each; 66 Group is one CLIENT for its remittance and its game-reseller business (D38)", "lead": "A client sends USDT (or a bank transfer) to pay a third party's invoice by bank transfer; quote-first, priced at the partner's rate plus NPL's markup.", "scenarios": [
  ["YN Remit", "Third-party invoices with a clear sending and receiving entity and KYC onboarded on Ali's PT channels; quote first at partner rate + 0.5 %; USDT to USD, EUR or GBP; occasionally NPL's own entity is the declared sender", "Variable 0.5-2.19 %; F2 in, F4/F5 out, F6 if returned, F9", "Quote-first DEAL_GROUP; DESTINATION_APPROVAL per route (invariant 8); SETTLEMENT_SENDING_ENTITY may be NPL's entity; FEE_STRUCTURE mode variable"],
  ["66 Group, multi-currency and INR cash", "Like YN Remit; INR almost always collected as cash at 7 % total (average 6 %, minimum margin 0.5 %), rounded to 1,000; a local INR account is arranged on demand for one transaction", "Variable, set per deal; F1 in (cash) or F7 (one-time local account), F5 out under NPL's name via PT Global", "FEE_STRUCTURE variable with min_markup_pct, max_markup_pct, min_margin_pct; cash_rounding to 1,000 (D25); DEAL.cash_location, token (D30); COLLECTION_RECEIVING_ENDPOINT usage single_use and LOSS_EVENT if an account is frozen (D32)"],
  ["GDC, fee by monthly volume", "USDT to USD at 1 : 1 plus 2.5 %, 2.25 % once the calendar-month volume passes USD 500,000, the crossing deal split; several receiving entities (Adu Ads, Ad Fusion, TDC, Pixel Labs); New Pinnacle Ltd contracts; minimum margin 1.8 %", "Tiered; F2 in, F5 out via PT Global, F9", "FEE_TIER with PROJECT_MONTH_VOLUME; DEAL_FEE_TIER portions, blended fee (D21); one RECEIVER with several RECEIVING_ENTITY_ACCOUNTs; SETTLEMENT_SENDING_ENTITY New Pinnacle Ltd"],
  ["Peru remittance", "Bank transfer to Ali's receiving entity PT Silver Lining Production, converted to USDT; Ali 3 % + NPL 1 %", "Fixed 4 %; F4 in, F3 then wallet payout", "PARTNER_PAIR fee_in_rate; bank-in endpoint with rail (D18)"]]},
 {"client": "JTN, Jonas (cash projects)", "projects": "JTN-JPY cash; Ad hoc INR cash", "lead": "USDT in, local cash out, or local cash in, USDT or USD out; the same party on both sides, priced per city, settled by token.", "scenarios": [
  ["JTN-JPY cash", "JTN sends USDT to Ali; Ali converts to JPY cash handed over by token; the day's rate is compared and quoted with a markup of 0.2-0.5 %, maximum 0.5 %; total fee 1-1.8 %", "Variable with a maximum markup; F2 in, F1 out", "FEE_STRUCTURE mode variable with max_markup_pct 0.5 %; sender equals receiver; SETTLEMENT_LINE.token_ref; DEAL.cash_location (D30)"],
  ["Ad hoc INR cash (Jonas)", "INR cash collected by token in a named city at 7 % total, paid out in USD, SGD or USDT; rates differ between Delhi and Mumbai", "Fixed 7 %; F1 in, wallet or F5 out", "DEAL.cash_location, PARTNER_RATE_VERSION.location, COLLECTION.token_ref, counted_at (D30); cash_rounding to 1,000 (D25)"]]},
 {"client": "AK Personal", "projects": "AK collections (USDT, INR)", "lead": "A stakeholder's account operated with Ali: collections and conversions as normal, but the balance stays at the partner and is paid out on request, with no markup.", "scenarios": [
  ["Held balance", "USDT (and INR) collected; balances kept in USD, SGD and USDT up to about USD 400,000 equivalent, revised from time to time", "0 %; F2 in", "FEE_STRUCTURE 0 % with min_margin 0 %; PROJECT.settlement_policy hold_allowed, exposure_ceiling; PROJECT_BALANCE view (per project), CLIENT_POSITION across the client's projects"],
  ["Conversions between held currencies", "10,000 USDT collected at night converts to SGD the next business morning: USD and SGD are banking-ready balances bound by the cutoff", "F9", "BALANCE_CONVERSION with rate_locked_at and conversion_due_date (D29); ENTITLEMENT_REATTRIBUTION"],
  ["Withdrawals on request", "Local bank payment, SWIFT, USDT or cash", "F8 (local), F5 (SWIFT), F3 then wallet, F1 (cash)", "SETTLEMENT with the matching rail; SETTLEMENT_LINE.token_ref for cash; RECEIVING_ENTITY_ACCOUNT single_use for a one-time local account (D30, D32)"]]},
 {"client": "Evolution (dormant)", "projects": "Evolution bank transfers and older currency products", "lead": "Not run for years but kept in scope by NPL: the fee still applies because the currency is collected and then settled separately.", "scenarios": [
  ["Same-currency pass-through (USD, EUR, GBP)", "A bank transfer in and the same currency out; 1.4 % from the sender and 1.4 % from Evolution", "2.8 %; F4 in, F5 out, F9", "CURRENCY_PAIR with equal sides, CONVERSION at rate 1 (D33); FEE_STRUCTURE sender_pays_pct 1.4 / receiver_pays_pct 1.4"],
  ["CNY, PHP, THB, SGD, HKD, AED and USD cash in Dubai", "Older products of the same client at 3.2-6.75 %; the cash rounding unit for Dubai is not yet given", "F4 or F1 in", "Standard pairs; cash_rounding_unit to be filled (D25)"]]},
]
FLOWS = [
 ["F1", "Cash by token (collection or settlement)", "Rate shared by afternoon HK time; token number and the agent's contact shared; hand-over against the token; photo of the token as proof; the partner counts and confirms; rates differ by city. Settlement is the same with the roles switched", "COLLECTION.token_ref, agent_contact_ref, evidence_ref, counted_at, states token_issued, handed_over, counted, verified; DEAL.cash_location; PARTNER_RATE_VERSION.location; SETTLEMENT_LINE.token_ref (D30)"],
 ["F2", "USDT collection with wallet screening", "Sender declares a wallet; NPL screens it; standard or alternate receiving wallet by risk; sender shares the hash; NPL verifies on chain; partner confirms. Not every Evo sender is screened", "WALLET_SCREENING (Operations); COLLECTION.sending_address, wallet_screening_id, screening_skipped; COLLECTION_RECEIVING_ENDPOINT.risk_band; invariant 30 (D31)"],
 ["F3", "Receiver wallet screened before settlement", "NPL screens the receiver's wallet, the partner executes, the hash is shared, the receiver confirms", "WALLET_SCREENING subject receiver_wallet; DESTINATION_APPROVAL.wallet_screening_id (D31)"],
 ["F4", "SWIFT collection", "Partner approves the sender from company profile and KYC and provides an account; proof of transfer exchanged; partner confirms; conversion per the agreed flow", "COLLECTION_SENDING_ENTITY; bank endpoint active only with its rail (D18) and matching the leg (D19); COLLECTION.evidence_ref, verified_by, verified_at"],
 ["F5", "SWIFT settlement", "Partner approves the destination and route before collection; transfer after collection; slip shared with the receiver; receiver confirms; a bank fee is occasionally covered; an unreceived transfer is chased through the banking channel", "DESTINATION_APPROVAL (invariant 8); SETTLEMENT, SETTLEMENT_RAIL, SETTLEMENT_SENDING_ENTITY; CONFIRMATION; BANK_FEE_EVENT with FEE_DECISION"],
 ["F6", "Returned transfer", "Resend, reuse the returned funds for another transfer, or reconvert and return to the sender", "SETTLEMENT_RETURN; reversing posting; return leg to the sender_return receiver (D13)"],
 ["F7", "One-time local deposit account", "The partner provides an ad hoc account for one transaction and amount; deposit or local transfer; proof exchanged; partner recognises the funds; a frozen account caused on the sender's side is a reversal of the collection; a loss can be partial or shared", "COLLECTION_RECEIVING_ENDPOINT usage single_use, reserved_for_deal_id, expected_amount; LOSS_EVENT with the four-way split, EXP_LOSS; COLLECTION state reversed (D32)"],
 ["F8", "Local payouts for small amounts", "Receiver gives a local account where the partner allows it (SG, HK, Indonesia, Thailand); the partner pays by cash deposit or local transfer and shares proof; receiver confirms; cash short at hand-over is adjusted later or paid separately", "RECEIVING_ENTITY_ACCOUNT usage single_use (D32); SHORTFALL topped up next settlement or by its own SETTLEMENT; LOSS_EVENT if unrecoverable"],
 ["F9", "Bank cutoff", "Per partner, for currencies that rely on bank transfer; binds the rate lock and the outgoing settlement; locked before 14:30 GMT+8 is same day, after it next business day; extendable 30-60 minutes if the partner agrees; closed early on Fridays or before a holiday", "PARTNER.bank_cutoff_time, PARTNER_CUTOFF_OVERRIDE, HOLIDAY; DEAL and SETTLEMENT cutoff_at and due dates; cutoff_timing variance (D29, D34)"],
 ["F10", "Internal transfer inside the partner's platform", "Aquanow moves EUR to BF's account on the same platform, instantly", "RECEIVING_ENTITY_ACCOUNT.rail internal; no bank fee on the rail (D18)"],
]
QUESTIONS_NPL = [
 "F2 — the 'alternate receiving wallets' for higher-risk senders: other wallets of the same partner, a different partner, or NPL's own wallet?",
 "F1 — cash settlement 'same process, roles switched': who provides the token for a payout, the receiver's side or the partner's agent, and who keeps the photo?",
 "F1 — does the cutoff bind a cash-in deal only when the payout side is a bank transfer?",
 "F1 — when the partner's count completes after the hand-over day, is the rate the morning's locked rate or the rate on the day of the count?",
 "F5 — who approves covering a bank fee on special cases, Finance or Management?",
 "F8 — is a partner's cash deposit into the receiver's bank account a local bank payout (no token) rather than a cash hand-over?",
 "Jeton — confirm it offers no cash or local-deposit methods.",
 "GDC — is the USD 500,000 counted for GDC as a whole? (assumed yes)",
 "27 Group THB — refuse the quote or only warn Finance when Ali's rate is more than 1.5 % below market? Any forex limit beyond the 2 % buffer?",
 "AK — after an overnight wait the rate used is the next morning's partner rate (to confirm).",
 "Novi via Jeton — 0.3 % rebate confirmed; the Jeton route is inactive, so the configuration is dormant.",
 "Cash — the rounding unit for AED and USD cash in Dubai.",
]
d["SCENARIO_CATALOGUE"] = {"intro": "Every scenario in NPL's Fee Outlines workbook (Sud's answers of 8 October 2026, with the Project Context and Payment methods tabs) runs through ERD v5.4. Scenarios are grouped by client and project; the operational flows they share are defined once (F1–F10) and referenced by number. Source: 'NPLify Scenario Catalogue v1.0' (9 October 2026).",
    "projects": PROJECTS, "flows": FLOWS, "open_questions": QUESTIONS_NPL}
P.write_text(json.dumps(d, ensure_ascii=False, indent=1) + "\n")
print("scenario catalogue:", sum(len(p["scenarios"]) for p in PROJECTS), "scenarios,", len(FLOWS), "flows,", len(QUESTIONS_NPL), "open questions")
